// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4sx9TBzu029F6NYXVFxsWttn2AlX032Q',
    appId: '1:37340488884:web:da6c042c25f906a14423e1',
    messagingSenderId: '37340488884',
    projectId: 'morenotesbynzima',
    authDomain: 'morenotesbynzima.firebaseapp.com',
    storageBucket: 'morenotesbynzima.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNHsNkLUcD-pkoM8Lx7_OEvSSgwY_S4bY',
    appId: '1:37340488884:android:b6d3b4e8e1a294be4423e1',
    messagingSenderId: '37340488884',
    projectId: 'morenotesbynzima',
    storageBucket: 'morenotesbynzima.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLOWKUJgn0e1XktieMk5urB4ojDmXP2GQ',
    appId: '1:37340488884:ios:368dfc7a879b9dcd4423e1',
    messagingSenderId: '37340488884',
    projectId: 'morenotesbynzima',
    storageBucket: 'morenotesbynzima.appspot.com',
    iosClientId: '37340488884-v8ocri0bjndt4gnd8lc6db3l8ufkd04m.apps.googleusercontent.com',
    iosBundleId: 'com.example.notesapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLOWKUJgn0e1XktieMk5urB4ojDmXP2GQ',
    appId: '1:37340488884:ios:368dfc7a879b9dcd4423e1',
    messagingSenderId: '37340488884',
    projectId: 'morenotesbynzima',
    storageBucket: 'morenotesbynzima.appspot.com',
    iosClientId: '37340488884-v8ocri0bjndt4gnd8lc6db3l8ufkd04m.apps.googleusercontent.com',
    iosBundleId: 'com.example.notesapp',
  );
}
